services:
  - type: web
    name: food-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/api.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.6
